compASM lfbDriver1
chmode lfbDriver1.code $44
renOW lfbDriver1.code \system\drivers\graphic\lfbDriver1.code

compASM lfbDriver8
chmode lfbDriver8.code $44
renOW lfbDriver8.code \system\drivers\graphic\lfbDriver8.code

compASM lfbDriver8pal
chmode lfbDriver8pal.code $44
renOW lfbDriver8pal.code \system\drivers\graphic\lfbDriver8pal.code

compASM lfbDriver15
chmode lfbDriver15.code $44
renOW lfbDriver15.code \system\drivers\graphic\lfbDriver15.code

compASM lfbDriver16
chmode lfbDriver16.code $44
renOW lfbDriver16.code \system\drivers\graphic\lfbDriver16.code

compASM lfbDriver24
chmode lfbDriver24.code $44
renOW lfbDriver24.code \system\drivers\graphic\lfbDriver24.code

compASM lfbDriver32
chmode lfbDriver32.code $44
renOW lfbDriver32.code \system\drivers\graphic\lfbDriver32.code

compASM lfbDriverTest
chmode lfbDriverTest.code $44
renOW lfbDriverTest.code \system\drivers\graphic\lfbDriverTest.code



compASM vgaSetMode
chmode vgaSetMode.code $44
renOW vgaSetMode.code \system\drivers\graphic\vgaSetMode.code

compASM vgaSetFont
chmode vgaSetFont.code $44
renOW vgaSetFont.code \system\drivers\graphic\vgaSetFont.code

compASM vgaSetPal
chmode vgaSetPal.code $44
renOW vgaSetPal.code \system\drivers\graphic\vgaSetPal.code
