#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_instance() {
        local par
        config_get par $1 param
        procd_open_instance
        procd_set_param command /usr/sbin/p4xdp.sh $par
        procd_set_param stderr 1
        procd_set_param stdout 1
        procd_close_instance
}

stop_instance() {
        local par
        config_get par $1 param
}

start_service() {
        config_load p4xdp
        config_foreach start_instance p4xdp
}

stop_service() {
        config_load p4xdp
        config_foreach start_instance p4xdp
}
