org 8000h
firstbyte:

bl startupCopy                  ;copy kernel to it's place...
lis r3,offset kernel_id2
ori r3,r3,offset kernel_id2
bl putOutAsciiZ                 ;put out logo...
bl memory_getFree               ;get free bytes...
bl exception_install            ;install exception handler...
bl memory_initAll               ;initialize memory system...
bl mmu_setup                    ;setup mmu state...
bl mmu_clear                    ;clear mmu state...
bl getCPUinfo                   ;get cpu info...
bl timer_install                ;install timer...
bl process_create               ;create one process...
bl process_updateRamdrv         ;update ramdrive...
bl process_begRun               ;start this one...
bl process_create               ;create one process...
bl process_updateIniter         ;update initer...
bl process_begRun               ;start this one...
b process_startNext             ;start next process...
;-------------------------------


;------------------------------- include files...
include datablk.inc             ;data structures...
include utils.inc               ;useful stuff...
;include mmu_tlb.inc             ;mmu stuff...
include mmu_bat.inc             ;mmu stuff...
include memory.inc              ;memory stuff...
include excint.inc              ;exception handlers...
include process.inc             ;process stuff...
include pipeline.inc            ;pipeline stuff...
include fileio.inc              ;fileio stuff...
include syscall0.inc            ;syscall servicer...
include syscall1.inc            ;syscall servicer...
include syscall2.inc            ;syscall servicer...
include syscall3.inc            ;syscall servicer...
include syscall4.inc            ;syscall servicer...
include crc32.inc               ;crc32 calculator...
;-------------------------------
kernelChecksum dd ?
lastbyte:
