compPAS systemInstaller
chmode systemInstaller.code $44
renOW systemInstaller.code \system\installer\systemInstaller.code

compPAS autoUpdater
chmode autoUpdater.code $44
renOW autoUpdater.code \system\installer\autoUpdater.code

compPAS networkConfig
chmode networkConfig.code $44
renOW networkConfig.code \system\installer\networkConfig.code

compPAS networkInstall
chmode networkInstall.code $44
renOW networkInstall.code \system\installer\networkInstall.code
