CompPAS ansi
chmode ansi.code $04
renOW ansi.code \utils\terminal\termOut-ansi.code

CompPAS ascii
chmode ascii.code $04
renOW ascii.code \utils\terminal\termOut-ascii.code

CompPAS avatar
chmode avatar.code $04
renOW avatar.code \utils\terminal\termOut-avatar.code

CompPAS ebcdic
chmode ebcdic.code $04
renOW ebcdic.code \utils\terminal\termOut-ebcdic.code

CompPAS raw
chmode raw.code $04
renOW raw.code \utils\terminal\termOut-raw.code
