compPAS serialTcpS
chmode serialTcpS.code $44
renOW serialTcpS.code \internet\kernel\serialTcpS.code

compPAS serialTcpC
chmode serialTcpC.code $44
renOW serialTcpC.code \internet\kernel\serialTcpC.code
