compASMn minibios.asm
noerr del minibios.rom
exec \utils\developer\utils\makerom.code minibios.code minibios.rom
del minibios.code
chmode minibios.rom 9
renOW minibios.rom \system\kernel\miniBiOS.rom
