compPAS makeKey_dss
chmode makeKey_dss.code $24
renOW makeKey_dss.code \utils\digsig\makeKey_dss.code

compPAS makeKey_rsa
chmode makeKey_rsa.code $24
renOW makeKey_rsa.code \utils\digsig\makeKey_rsa.code



compPAS readGroup_dh
chmode readGroup_dh.code $24
renOW readGroup_dh.code \utils\digsig\readGroup_dh.code

compPAS asn1parse
chmode asn1parse.code $24
renOW asn1parse.code \utils\digsig\asn1parse.code



compPAS importPrivKey_dss
chmode importPrivKey_dss.code $24
renOW importPrivKey_dss.code \utils\digsig\importPrivKey_dss.code

compPAS importPrivKey_rsa
chmode importPrivKey_rsa.code $24
renOW importPrivKey_rsa.code \utils\digsig\importPrivKey_rsa.code



compPAS importPubKey_dss
chmode importPubKey_dss.code $24
renOW importPubKey_dss.code \utils\digsig\importPubKey_dss.code

compPAS importPubKey_rsa
chmode importPubKey_rsa.code $24
renOW importPubKey_rsa.code \utils\digsig\importPubKey_rsa.code



compPAS exportPrivKey_dss
chmode exportPrivKey_dss.code $24
renOW exportPrivKey_dss.code \utils\digsig\exportPrivKey_dss.code

compPAS exportPrivKey_rsa
chmode exportPrivKey_rsa.code $24
renOW exportPrivKey_rsa.code \utils\digsig\exportPrivKey_rsa.code



compPAS exportPubKey_dss
chmode exportPubKey_dss.code $24
renOW exportPubKey_dss.code \utils\digsig\exportPubKey_dss.code

compPAS exportPubKey_rsa
chmode exportPubKey_rsa.code $24
renOW exportPubKey_rsa.code \utils\digsig\exportPubKey_rsa.code



compPAS request_dss
chmode request_dss.code $24
renOW request_dss.code \utils\digsig\request_dss.code

compPAS request_rsa
chmode request_rsa.code $24
renOW request_rsa.code \utils\digsig\request_rsa.code



compPAS selfSign_dss
chmode selfSign_dss.code $24
renOW selfSign_dss.code \utils\digsig\selfSign_dss.code

compPAS selfSign_rsa
chmode selfSign_rsa.code $24
renOW selfSign_rsa.code \utils\digsig\selfSign_rsa.code



compPAS signReq_dss
chmode signReq_dss.code $24
renOW signReq_dss.code \utils\digsig\signReq_dss.code

compPAS signReq_rsa
chmode signReq_rsa.code $24
renOW signReq_rsa.code \utils\digsig\signReq_rsa.code



compPAS fileSigner_dss
chmode fileSigner_dss.code $24
renOW fileSigner_dss.code \utils\digsig\fileSigner_dss.code

compPAS fileSigner_rsa
chmode fileSigner_rsa.code $24
renOW fileSigner_rsa.code \utils\digsig\fileSigner_rsa.code



compPAS fileVerify_dss
chmode fileVerify_dss.code $24
renOW fileVerify_dss.code \utils\digsig\fileVerify_dss.code

compPAS fileVerify_rsa
chmode fileVerify_rsa.code $24
renOW fileVerify_rsa.code \utils\digsig\fileVerify_rsa.code
