CompPAS clock
chmode clock.code $64
renOW clock.code \utils\scrsaver\clock.code

CompPAS fire
chmode fire.code $64
renOW fire.code \utils\scrsaver\fire.code

CompPAS life
chmode life.code $64
renOW life.code \utils\scrsaver\life.code

CompPAS snake
chmode snake.code $64
renOW snake.code \utils\scrsaver\snake.code
