compPAS ip6
chmode ip6.code $44
renOW ip6.code \internet\kernel\ip6.code

compPAS ip6conf
chmode ip6conf.code $44
renOW ip6conf.code \internet\kernel\ip6conf.code

compPAS ip6iface
chmode ip6iface.code $44
renOW ip6iface.code \internet\kernel\ip6iface.code
