compPAS streamForwardS
chmode streamForwardS.code $44
renOW streamForwardS.code \internet\server\streamForwardS.code

compPAS streamForwardC
chmode streamForwardC.code $44
renOW streamForwardC.code \internet\server\streamForwardC.code
