compPAS bookmark2html
chmode bookmark2html.code $24
renOW bookmark2html.code \internet\client\bookmark2html.code

compPAS browser
chmode browser.code $24
renOW browser.code \internet\client\browser.code

compPAS mirror
chmode mirror.code $24
renOW mirror.code \internet\client\mirror.code
