org 100h
use16
firstbyte:
;-------------------------------
call copyCode2final
call general_initialize
call memory_initialize
call handle_initialize
call video_initialize
call dos_initialize
call setup_zero_page
call interrupts_clear
mov si,offset bios_interrupts
call interrupts_hook
mov si,offset dos_interrupts
call interrupts_hook
call portio_initialize
call timer_initialize

mov si,offset main_txt01
call write
mov si,offset main_txt02
call write
mov si,offset textCRLF
call write

call repairParams
call dos_startProc

jmp terminate
;-------------------------------

;-------------------------------
textMyName db 13,10,'dosemu: ',0
main_txt01 db 'dosEmu v1.0',0
main_txt02 db ', done by Mc at ',%date,' ',%time,'.',0
main_txt03 db 'using: dosemu.v86 <dos program>',0
;-------------------------------

;------------------------------- general purpose...
align 4
data_temp0 db 512 dup (?)       ;temporary data...
data_temp1 db 512 dup (?)       ;temporary data...
data_temp2 dd ?                 ;temporary data...
data_temp3 dd ?                 ;temporary data...
data_temp4 dd ?                 ;temporary data...
data_temp5 dd ?                 ;temporary data...
data_temp6 dd ?                 ;temporary data...
data_temp7 dd ?                 ;temporary data...
data_temp8 dd ?                 ;temporary data...
data_temp9 dd ?                 ;temporary data...
;-------------------------------

;-------------------------------
proc repairParams
sub ax,ax
mov def:[data_temp2],ax
mov ax,cs
mov ds,ax
mov es,ax
mov si,offset data_temp0
mov di,offset lastbyte
lodsb
movzx cx,al
or cx,cx
jz byte repairParams_j1
rep
  movsb
sub ax,ax
stosw
mov si,offset lastbyte
mov di,offset data_temp0
call dos_pathPatch
ret
repairParams_j1:
mov si,offset main_txt03
call write
mov si,offset textCRLF
call write
jmp terminate
endp
;-------------------------------

;-------------------------------
dos_interrupts:
dw 20h,offset int20h
dw 21h,offset int21h
dw 25h,offset int25h
dw 26h,offset int25h
dw 27h,offset int27h
dw 2fh,offset int2fh
dw 0ffffh
;-------------------------------


;------------------------------- includes...
include biosemu_int10.inc       ;interrupt handler...
include biosemu_int11.inc       ;interrupt handler...
include biosemu_int12.inc       ;interrupt handler...
include biosemu_int13.inc       ;interrupt handler...
include biosemu_int14.inc       ;interrupt handler...
include biosemu_int15.inc       ;interrupt handler...
include biosemu_int16.inc       ;interrupt handler...
include biosemu_int17.inc       ;interrupt handler...
include biosemu_int19.inc       ;interrupt handler...
include biosemu_int1a.inc       ;interrupt handler...
include biosemu_intXX.inc       ;interrupt handler...
include biosemu_disk.inc        ;disk io...
include biosemu_keyb.inc        ;keyboard io...
include biosemu_port.inc        ;port io...
include biosemu_serial.inc      ;serial io...
include biosemu_syscall.inc     ;kernel calls...
include biosemu_timer.inc       ;timer io...
include biosemu_utils.inc       ;general functions...
include biosemu_video.inc       ;video io...
include dosemu_int20.inc        ;interrupt handler...
include dosemu_int21.inc        ;interrupt handler...
include dosemu_int25.inc        ;interrupt handler...
include dosemu_int27.inc        ;interrupt handler...
include dosemu_int2f.inc        ;interrupt handler...
include dosemu_handle.inc       ;file/dir handles...
include dosemu_memory.inc       ;memory management...
include dosemu_process.inc      ;process management...
;-------------------------------
lastbyte:
