compASM biosEmu
chmode biosEmu.code $09
renOW biosEmu.code \system\v86utils\biosEmu.v86

compASM dosEmu
chmode dosEmu.code $09
renOW dosEmu.code \system\v86utils\dosEmu.v86



compASM batteryStatus
chmode batteryStatus.code $09
renOW batteryStatus.code \system\v86utils\batteryStatus.v86



compASM cpuid
chmode cpuid.code $09
renOW cpuid.code \system\v86utils\cpuid.v86



compASM setMode320x200
chmode setMode320x200.code $01
renOW setMode320x200.code \system\v86utils\setMode320x200.v86

compASM setMode80x25
chmode setMode80x25.code $01
renOW setMode80x25.code \system\v86utils\setMode80x25.v86

compASM setMode40x25
chmode setMode40x25.code $01
renOW setMode40x25.code \system\v86utils\setMode40x25.v86

compASM setMode80x50
chmode setMode80x50.code $01
renOW setMode80x50.code \system\v86utils\setMode80x50.v86

compASM setMode40x50
chmode setMode40x50.code $01
renOW setMode40x50.code \system\v86utils\setMode40x50.v86

compASM setMode640x480
chmode setMode640x480.code $01
renOW setMode640x480.code \system\v86utils\setMode640x480.v86



compASM turnSystemOff
chmode turnSystemOff.code $01
renOW turnSystemOff.code \system\v86utils\turnSystemOff.v86

compASM turnMonitorOff
chmode turnMonitorOff.code $01
renOW turnMonitorOff.code \system\v86utils\turnMonitorOff.v86

compASM turnMonitorOn
chmode turnMonitorOn.code $01
renOW turnMonitorOn.code \system\v86utils\turnMonitorOn.v86



compASM vesaListModes
chmode vesaListModes.code $01
renOW vesaListModes.code \system\v86utils\vesaListModes.v86

compASM vesaModeInfo
chmode vesaModeInfo.code $01
renOW vesaModeInfo.code \system\v86utils\vesaModeInfo.v86

compASM vesaSetMode
chmode vesaSetMode.code $01
renOW vesaSetMode.code \system\v86utils\vesaSetMode.v86
