compPAS friends2html
chmode friends2html.code $24
renOW friends2html.code \internet\client\friends2html.code

compPAS mailer
chmode mailer.code $64
renOW mailer.code \internet\client\mailer.code
