#!/bin/sh
java -cp /nfs/own/web/player duplicates /nfs/temp/\!new/
java -cp /nfs/own/web/player duplicates /nfs/music/0/
java -cp /nfs/own/web/player duplicates /nfs/music/a/
java -cp /nfs/own/web/player duplicates /nfs/music/b/
java -cp /nfs/own/web/player duplicates /nfs/music/c/
java -cp /nfs/own/web/player duplicates /nfs/music/d/
java -cp /nfs/own/web/player duplicates /nfs/music/e/
java -cp /nfs/own/web/player duplicates /nfs/music/f/
java -cp /nfs/own/web/player duplicates /nfs/music/g/
java -cp /nfs/own/web/player duplicates /nfs/music/h/
java -cp /nfs/own/web/player duplicates /nfs/music/i/
java -cp /nfs/own/web/player duplicates /nfs/music/j/
java -cp /nfs/own/web/player duplicates /nfs/music/k/
java -cp /nfs/own/web/player duplicates /nfs/music/l/
java -cp /nfs/own/web/player duplicates /nfs/music/m/
java -cp /nfs/own/web/player duplicates /nfs/music/n/
java -cp /nfs/own/web/player duplicates /nfs/music/o/
java -cp /nfs/own/web/player duplicates /nfs/music/p/
java -cp /nfs/own/web/player duplicates /nfs/music/q/
java -cp /nfs/own/web/player duplicates /nfs/music/r/
java -cp /nfs/own/web/player duplicates /nfs/music/s/
java -cp /nfs/own/web/player duplicates /nfs/music/t/
java -cp /nfs/own/web/player duplicates /nfs/music/u/
java -cp /nfs/own/web/player duplicates /nfs/music/v/
java -cp /nfs/own/web/player duplicates /nfs/music/w/
java -cp /nfs/own/web/player duplicates /nfs/music/x/
java -cp /nfs/own/web/player duplicates /nfs/music/y/
java -cp /nfs/own/web/player duplicates /nfs/music/z/
