#!/bin/sh
mv /nfs/temp/\!new/0* /nfs/music/0/
mv /nfs/temp/\!new/1* /nfs/music/0/
mv /nfs/temp/\!new/2* /nfs/music/0/
mv /nfs/temp/\!new/3* /nfs/music/0/
mv /nfs/temp/\!new/4* /nfs/music/0/
mv /nfs/temp/\!new/5* /nfs/music/0/
mv /nfs/temp/\!new/6* /nfs/music/0/
mv /nfs/temp/\!new/7* /nfs/music/0/
mv /nfs/temp/\!new/8* /nfs/music/0/
mv /nfs/temp/\!new/9* /nfs/music/0/
mv /nfs/temp/\!new/A* /nfs/music/a/
mv /nfs/temp/\!new/B* /nfs/music/b/
mv /nfs/temp/\!new/C* /nfs/music/c/
mv /nfs/temp/\!new/D* /nfs/music/d/
mv /nfs/temp/\!new/E* /nfs/music/e/
mv /nfs/temp/\!new/F* /nfs/music/f/
mv /nfs/temp/\!new/G* /nfs/music/g/
mv /nfs/temp/\!new/H* /nfs/music/h/
mv /nfs/temp/\!new/I* /nfs/music/i/
mv /nfs/temp/\!new/J* /nfs/music/j/
mv /nfs/temp/\!new/K* /nfs/music/k/
mv /nfs/temp/\!new/L* /nfs/music/l/
mv /nfs/temp/\!new/M* /nfs/music/m/
mv /nfs/temp/\!new/N* /nfs/music/n/
mv /nfs/temp/\!new/O* /nfs/music/o/
mv /nfs/temp/\!new/P* /nfs/music/p/
mv /nfs/temp/\!new/Q* /nfs/music/q/
mv /nfs/temp/\!new/R* /nfs/music/r/
mv /nfs/temp/\!new/S* /nfs/music/s/
mv /nfs/temp/\!new/T* /nfs/music/t/
mv /nfs/temp/\!new/U* /nfs/music/u/
mv /nfs/temp/\!new/V* /nfs/music/v/
mv /nfs/temp/\!new/W* /nfs/music/w/
mv /nfs/temp/\!new/X* /nfs/music/x/
mv /nfs/temp/\!new/Y* /nfs/music/y/
mv /nfs/temp/\!new/Z* /nfs/music/z/
