#!/bin/sh
mv /nfs2/temp/\!new/0* /nfs2/music/0/
mv /nfs2/temp/\!new/1* /nfs2/music/0/
mv /nfs2/temp/\!new/2* /nfs2/music/0/
mv /nfs2/temp/\!new/3* /nfs2/music/0/
mv /nfs2/temp/\!new/4* /nfs2/music/0/
mv /nfs2/temp/\!new/5* /nfs2/music/0/
mv /nfs2/temp/\!new/6* /nfs2/music/0/
mv /nfs2/temp/\!new/7* /nfs2/music/0/
mv /nfs2/temp/\!new/8* /nfs2/music/0/
mv /nfs2/temp/\!new/9* /nfs2/music/0/
mv /nfs2/temp/\!new/A* /nfs2/music/a/
mv /nfs2/temp/\!new/B* /nfs2/music/b/
mv /nfs2/temp/\!new/C* /nfs2/music/c/
mv /nfs2/temp/\!new/D* /nfs2/music/d/
mv /nfs2/temp/\!new/E* /nfs2/music/e/
mv /nfs2/temp/\!new/F* /nfs2/music/f/
mv /nfs2/temp/\!new/G* /nfs2/music/g/
mv /nfs2/temp/\!new/H* /nfs2/music/h/
mv /nfs2/temp/\!new/I* /nfs2/music/i/
mv /nfs2/temp/\!new/J* /nfs2/music/j/
mv /nfs2/temp/\!new/K* /nfs2/music/k/
mv /nfs2/temp/\!new/L* /nfs2/music/l/
mv /nfs2/temp/\!new/M* /nfs2/music/m/
mv /nfs2/temp/\!new/N* /nfs2/music/n/
mv /nfs2/temp/\!new/O* /nfs2/music/o/
mv /nfs2/temp/\!new/P* /nfs2/music/p/
mv /nfs2/temp/\!new/Q* /nfs2/music/q/
mv /nfs2/temp/\!new/R* /nfs2/music/r/
mv /nfs2/temp/\!new/S* /nfs2/music/s/
mv /nfs2/temp/\!new/T* /nfs2/music/t/
mv /nfs2/temp/\!new/U* /nfs2/music/u/
mv /nfs2/temp/\!new/V* /nfs2/music/v/
mv /nfs2/temp/\!new/W* /nfs2/music/w/
mv /nfs2/temp/\!new/X* /nfs2/music/x/
mv /nfs2/temp/\!new/Y* /nfs2/music/y/
mv /nfs2/temp/\!new/Z* /nfs2/music/z/
