#!/bin/sh
./nonAscii2.sh /nfs/music/0/
./nonAscii2.sh /nfs/music/a/
./nonAscii2.sh /nfs/music/b/
./nonAscii2.sh /nfs/music/c/
./nonAscii2.sh /nfs/music/d/
./nonAscii2.sh /nfs/music/e/
./nonAscii2.sh /nfs/music/f/
./nonAscii2.sh /nfs/music/g/
./nonAscii2.sh /nfs/music/h/
./nonAscii2.sh /nfs/music/i/
./nonAscii2.sh /nfs/music/j/
./nonAscii2.sh /nfs/music/k/
./nonAscii2.sh /nfs/music/l/
./nonAscii2.sh /nfs/music/m/
./nonAscii2.sh /nfs/music/n/
./nonAscii2.sh /nfs/music/o/
./nonAscii2.sh /nfs/music/p/
./nonAscii2.sh /nfs/music/q/
./nonAscii2.sh /nfs/music/r/
./nonAscii2.sh /nfs/music/s/
./nonAscii2.sh /nfs/music/t/
./nonAscii2.sh /nfs/music/u/
./nonAscii2.sh /nfs/music/v/
./nonAscii2.sh /nfs/music/w/
./nonAscii2.sh /nfs/music/x/
./nonAscii2.sh /nfs/music/y/
./nonAscii2.sh /nfs/music/z/
