#!/bin/sh
java -cp /nfs/own/web/player renamer /nfs2/temp/new/
java -cp /nfs/own/web/player renamer /nfs2/music/0/
java -cp /nfs/own/web/player renamer /nfs2/music/a/
java -cp /nfs/own/web/player renamer /nfs2/music/b/
java -cp /nfs/own/web/player renamer /nfs2/music/c/
java -cp /nfs/own/web/player renamer /nfs2/music/d/
java -cp /nfs/own/web/player renamer /nfs2/music/e/
java -cp /nfs/own/web/player renamer /nfs2/music/f/
java -cp /nfs/own/web/player renamer /nfs2/music/g/
java -cp /nfs/own/web/player renamer /nfs2/music/h/
java -cp /nfs/own/web/player renamer /nfs2/music/i/
java -cp /nfs/own/web/player renamer /nfs2/music/j/
java -cp /nfs/own/web/player renamer /nfs2/music/k/
java -cp /nfs/own/web/player renamer /nfs2/music/l/
java -cp /nfs/own/web/player renamer /nfs2/music/m/
java -cp /nfs/own/web/player renamer /nfs2/music/n/
java -cp /nfs/own/web/player renamer /nfs2/music/o/
java -cp /nfs/own/web/player renamer /nfs2/music/p/
java -cp /nfs/own/web/player renamer /nfs2/music/q/
java -cp /nfs/own/web/player renamer /nfs2/music/r/
java -cp /nfs/own/web/player renamer /nfs2/music/s/
java -cp /nfs/own/web/player renamer /nfs2/music/t/
java -cp /nfs/own/web/player renamer /nfs2/music/u/
java -cp /nfs/own/web/player renamer /nfs2/music/v/
java -cp /nfs/own/web/player renamer /nfs2/music/w/
java -cp /nfs/own/web/player renamer /nfs2/music/x/
java -cp /nfs/own/web/player renamer /nfs2/music/y/
java -cp /nfs/own/web/player renamer /nfs2/music/z/
