compPAS graphiCon
chmode graphiCon.code $44
renOW graphiCon.code \system\graphic\graphiCon.code

compPAS graphiCfg
chmode graphiCfg.code $44
renOW graphiCfg.code \system\graphic\graphiCfg.code

compPAS graphiTest
chmode graphiTest.code $44
renOW graphiTest.code \system\graphic\graphiTest.code

compPAS rotate
chmode rotate.code $44
renOW rotate.code \system\graphic\rotate.code

compPAS mirror
chmode mirror.code $44
renOW mirror.code \system\graphic\mirror.code
