compASM pci_devices
chmode pci_devices.code $44
renOW pci_devices.code \system\drivers\system\pci_devices.code

compASM cmos_saver
chmode cmos_saver.code $44
renOW cmos_saver.code \system\drivers\system\cmos_saver.code

compASM cmos_loader
chmode cmos_loader.code $44
renOW cmos_loader.code \system\drivers\system\cmos_loader.code

compASM setDateTime
chmode setDateTime.code $44
renOW setDateTime.code \system\drivers\system\setDateTime.code

compASM savePort
chmode savePort.code $44
renOW savePort.code \system\drivers\system\savePort.code

compASM saveMem
chmode saveMem.code $44
renOW saveMem.code \system\drivers\system\saveMem.code

compASM irqLister
chmode irqLister.code $44
renOW irqLister.code \system\drivers\system\irqLister.code

compASM isapnp_devices
chmode isapnp_devices.code $44
renOW isapnp_devices.code \system\drivers\system\isapnp_devices.code

compASM pcmcia_devices
chmode pcmcia_devices.code $44
renOW pcmcia_devices.code \system\drivers\system\pcmcia_devices.code
