compPAS dtl1
chmode dtl1.code $44
renOW dtl1.code \system\communication\bluetooth-dtl1.code

compPAS hci
chmode hci.code $44
renOW hci.code \system\communication\bluetooth-hci.code

compPAS hcitool
chmode hcitool.code $44
renOW hcitool.code \system\communication\bluetooth-hcitool.code
