CompPAS bmp
chmode bmp.code $24
renOW bmp.code \utils\graphic\filter-bmp.code

CompPAS cip
chmode cip.code $24
renOW cip.code \utils\graphic\filter-cip.code

CompPAS dra
chmode dra.code $24
renOW dra.code \utils\graphic\filter-dra.code

CompPAS drg
chmode drg.code $24
renOW drg.code \utils\graphic\filter-drg.code

CompPAS wbmp
chmode wbmp.code $24
renOW wbmp.code \utils\graphic\filter-wbmp.code
