compPAS bc
chmode bc.code $24
renOW bc.code \utils\bc-main.code

compASM launcher-i80386
chmode launcher-i80386.code $24
copyOW launcher-i80386.code \bc
chmode \bc $24
renOW launcher-i80386.code \utils\bc-launcher-i80386.code
