#! /bin/sh

### BEGIN INIT INFO
# Provides:          rtr
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: router processes
### END INIT INFO

case "$1" in
  start)
        cd /home/mc36
        /bin/busybox start-stop-daemon -S -b -x ./cons.bin
        /bin/busybox start-stop-daemon -S -b -x ./ovs.sh
        ;;
  stop)
        ;;
  status)
        ;;
  restart)
        $0 stop
        $0 start
  ;;
  *)
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
