package org.freertr.util;

/**
 * version information
 *
 * @author matecsaba
 */
public class version {

    private version() {
    }

    /**
     * os name
     */
    public final static String name = "freeRouter";

    /**
     * author
     */
    public final static String author = "sprscc13@mrn0b0dy";

    /**
     * current public key
     */
    public final static String pubKeyC = "MIIEeTANBgkqhkiG9w0BAQEFAAOCBGYAMIIEYQKCBFgAu3ipMu833fNcLGpnc/Iv47phAsMBect4SWo57IImx1DFqbkm0YeC1My8ktErYLWSwnu/ayKiujKvE4gsNQba7T6WNhn3sAq7YmS+qTHBUGuCRM1MsTW7bkkWJTvHyf8+TegQTncV0snR7K5jEK12mEE+hgopOvmlkdrduj/UAMW79l7qFZezJdZKUX7By/aehj7NIJahV+aTG7RCsC+4LofywvAY8o6BLzM2G/g9NWLQ1p7BQOJ67z1FBlRVsXxO8Buw9Ke7hitcIoJ5+UI6I+fiUyKsOciTGxa2NeaekZ56PKEwa9c4/f5B92Pbe1eh8OOkrPd7A9GUj3xZADSkWaXrhzGTjfEQIciZ9GvkO/dYjCnKUFXsBr23SzdkMgT+WisbrtP8Uk0AgYc3+DEXnufxc49m7OAYLycnb6Jzs+TFK7Fjix+DSsIZGu3Xzl6eVxK0pEYK9Pv15l9G/Y15oxqoEejq1tj1nijByUvUKzPzCTXq6Eh5pn1zOfZnDGq+WqDXL8jvUiV4a9jLfGYcKefgRfzriuq37iMk9NGygzvER4mj35ZzN2Un9F0+T0g81VhI+AZgyoccG3PYvdV8Kw/jUBI9t3qgy3czEvfCMO59EIdyX4xn7T3rF8b0W8VeAPUd+QHiOwXPLk1jtgPLX8xgk6hNhx8EAxdLZv13DmyjGZRLDxwYK9RdM2UlZhR9ykvk5MxAgyVDfQixQ3VXHZI5bOhcjghJoP9dFux53REQbZEzYDF/okHPKOwqTWkw03zT1xgpq7NYiqXvuWLA6Yr7jB9/+TEAEZrDUw6BtzuSSom12S4WJRwrDm48KqqvTZvDumr9AOmzSd69A+6sEIBxL0K1CNJ0SCxF+Ws+NhGaYoCRUr+gr3qjVJ782RZ5Zaf4i854vaZ9nNenM902W+YIdhARs01FvvFahj/UA/3mWF96GLDGZQH+utLVRACJo0uskAbWDYaD/FTgYX7q/c9vRn/E6HBhG4a2/5wSNAAQrvXAqthL0rPPi2i50gUjVD4nzXK7se6+8iJ2YGcrGL79EBvsMgAK75rx2ShOb1TDnVzL1SL02qmZ6AvRCVokcmH3+LxfM6X1HZWyeWj9NDW5mrS8SgRl2thRjLWpyLb7pyt+wo2KwRfgFQR3VDNwFgO+ZukHnvXxfqZcvpirVDCG4aul+z0UEB8H5dY2EMX67jvDrXz2zlRKwffzBTDWQyfdWNQH3bBLmpcojA2GFZMZypKV43GUMohi/8+Bzg6MFXYHE+XJiCf3dz3omhmh7VOwOzvU9cx/zJHqrrW9UAExbOgdh1q97jST9k3yrrSeMvGEutrU7jO3d/dEt/e0Hngpuntry1P/rFNNPqF8E07h1xbIeA1UD0l1pETVevpQd5MULSMthbN7kburH+yUngs1yv8Xr6xsB90d4MLx7U33LHA28lTiSEDzkALv6/rcq/YNFApYnIT5qBxj8Iov9Hg9g+EABQIDAQAB";

    /**
     * old public key
     */
    public final static String pubKeyO = "MIIEeTANBgkqhkiG9w0BAQEFAAOCBGYAMIIEYQKCBFgAu3ipMu833fNcLGpnc/Iv47phAsMBect4SWo57IImx1DFqbkm0YeC1My8ktErYLWSwnu/ayKiujKvE4gsNQba7T6WNhn3sAq7YmS+qTHBUGuCRM1MsTW7bkkWJTvHyf8+TegQTncV0snR7K5jEK12mEE+hgopOvmlkdrduj/UAMW79l7qFZezJdZKUX7By/aehj7NIJahV+aTG7RCsC+4LofywvAY8o6BLzM2G/g9NWLQ1p7BQOJ67z1FBlRVsXxO8Buw9Ke7hitcIoJ5+UI6I+fiUyKsOciTGxa2NeaekZ56PKEwa9c4/f5B92Pbe1eh8OOkrPd7A9GUj3xZADSkWaXrhzGTjfEQIciZ9GvkO/dYjCnKUFXsBr23SzdkMgT+WisbrtP8Uk0AgYc3+DEXnufxc49m7OAYLycnb6Jzs+TFK7Fjix+DSsIZGu3Xzl6eVxK0pEYK9Pv15l9G/Y15oxqoEejq1tj1nijByUvUKzPzCTXq6Eh5pn1zOfZnDGq+WqDXL8jvUiV4a9jLfGYcKefgRfzriuq37iMk9NGygzvER4mj35ZzN2Un9F0+T0g81VhI+AZgyoccG3PYvdV8Kw/jUBI9t3qgy3czEvfCMO59EIdyX4xn7T3rF8b0W8VeAPUd+QHiOwXPLk1jtgPLX8xgk6hNhx8EAxdLZv13DmyjGZRLDxwYK9RdM2UlZhR9ykvk5MxAgyVDfQixQ3VXHZI5bOhcjghJoP9dFux53REQbZEzYDF/okHPKOwqTWkw03zT1xgpq7NYiqXvuWLA6Yr7jB9/+TEAEZrDUw6BtzuSSom12S4WJRwrDm48KqqvTZvDumr9AOmzSd69A+6sEIBxL0K1CNJ0SCxF+Ws+NhGaYoCRUr+gr3qjVJ782RZ5Zaf4i854vaZ9nNenM902W+YIdhARs01FvvFahj/UA/3mWF96GLDGZQH+utLVRACJo0uskAbWDYaD/FTgYX7q/c9vRn/E6HBhG4a2/5wSNAAQrvXAqthL0rPPi2i50gUjVD4nzXK7se6+8iJ2YGcrGL79EBvsMgAK75rx2ShOb1TDnVzL1SL02qmZ6AvRCVokcmH3+LxfM6X1HZWyeWj9NDW5mrS8SgRl2thRjLWpyLb7pyt+wo2KwRfgFQR3VDNwFgO+ZukHnvXxfqZcvpirVDCG4aul+z0UEB8H5dY2EMX67jvDrXz2zlRKwffzBTDWQyfdWNQH3bBLmpcojA2GFZMZypKV43GUMohi/8+Bzg6MFXYHE+XJiCf3dz3omhmh7VOwOzvU9cx/zJHqrrW9UAExbOgdh1q97jST9k3yrrSeMvGEutrU7jO3d/dEt/e0Hngpuntry1P/rFNNPqF8E07h1xbIeA1UD0l1pETVevpQd5MULSMthbN7kburH+yUngs1yv8Xr6xsB90d4MLx7U33LHA28lTiSEDzkALv6/rcq/YNFApYnIT5qBxj8Iov9Hg9g+EABQIDAQAB";

    /**
     * compile year
     */
    public final static int year = 26;

    /**
     * compile month
     */
    public final static int month = 1;

    /**
     * compile day
     */
    public final static int day = 28;

    /**
     * statement of release
     */
    public final static String state = "-cur";

    /**
     * url1 of product
     */
    public final static String homeUrl = "http://www.freertr.org/";

    /**
     * license text
     */
    public final static String[] license = {
        "place on the web: " + homeUrl,
        "license: http://creativecommons.org/licenses/by-sa/4.0/",
        "the beer-ware license for selected group of people:",
        author + " wrote these files. as long as you retain this notice you",
        "can do whatever you want with this stuff. if we meet some day, and",
        "you think this stuff is worth it, you can buy me a beer in return"
    };

    /**
     * quotes text
     */
    public final static String[] quotes = {
        "",
        "quotes from devvies like " + author + ":",
        "true random comes from weather forecasts and political announcements",
        "if a machine can learn the value of human life, maybe we can too",
        "be liberal in what you accept, and conservative in what you send",
        "rough consensus and running code, keep it stupid simple",
        "dont drive faster than your guardian angel can fly",
        "care about the bits and not the bits of the bits",
        "let bloom all the flowers, make the world better",
        "the great power comes great responsibility",
        "every tool could be used for good or bad",
        "do or not to do but dont try"
    };

    /**
     * logo text
     */
    public final static String[] logo = {
        "  ####                       ##################",
        " ##                                  ##",
        " ##  ## ###   #####   #####  ## ###  ## ## ###",
        "####  ### ## ##   ## ##   ##  ### ## ##  ### ##",
        " ##   ##  ## ####### #######  ##  ## ##  ##  ##",
        " ##   ##     ##      ##       ##     ##  ##",
        " ##   ##     ##   ## ##   ##  ##     ##  ##",
        " ##   ##      #####   #####   ##     ##  ##"
    };

    /**
     * secret texts
     */
    public final static String[][] secrets = {
        {"key",
            "",
            "   /~~!~\\",
            "  |      |_______",
            "  | |<3Y |       |",
            "   \\____/        |",
            "",},
        {"love",
            "",
            "   /~~\\   /~~\\",
            "  |    \\_/    |",
            "   \\         /",
            "    \\  L0v3 /",
            "     \\     /",
            "      \\   /",
            "       \\ /",
            "        V",
            "",},
        {"bug",
            "",
            "                 \\   /",
            "                 .\\-/.",
            "             /\\  @o o@  /\\",
            "            /  \\ /~-~\\ /  \\",
            "                y  Y  V",
            "          ,-^-./   |   \\,-^-.",
            "         /    {   BuG   }    \\",
            "               \\   |   /",
            "               /\\  A  /\\",
            "              /  \\/ \\/  \\",
            "             /           \\",
            "",},
        {"xmastree",
            "                   \\ /",
            "                 -->*<--",
            "                   /o\\",
            "                  /_\\_\\",
            "                 /_/_0_\\",
            "                /_o_\\_\\_\\",
            "               /_/_/_/_/o\\",
            "              /@\\_\\_\\@\\_\\_\\",
            "             /_/_/O/_/_/_/_\\",
            "            /_\\_\\_\\_\\_\\o\\_\\_\\",
            "           /_/0/_/_/_0_/_/@/_\\",
            "          /_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\",
            "         /_/o/_/_/@/_/_/o/_/0/_\\",
            "            [___]",
            "b3ar pspsps sh0w m0r3 r3sp3ct y0urs3lv3s",},
        {"duck",
            "        ,----,",
            "   ___.`      `,",
            "   `===  D     :",
            "     `'.      .'",
            "        )    (                   ,",
            "       /      \\_________________/|",
            "      /                          |",
            "     |                           ;",
            "     |               _____       /",
            "     |      \\       ______7    ,'",
            "     |       \\    ______7     /",
            "      \\       `-,____7      ,'",
            "^~^~^~^`\\                  /~^~^~^~^",
            "  ~^~^~^ `----------------' ~^~^~^",
            " ~^~^~^~^~^^~^~^~^~^~^~^~^~^~^~^~",},
        {"disk",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "8                                                   8",
            "8  a---------------a                                8",
            "8  |               |                                8",
            "8  |               |                                8",
            "8  |               |                               8\"",
            "8  \"---------------\"                               8a",
            "8                                                   8",
            "8                                                   8",
            "8                      ,aaaaa,                      8",
            "8                    ad\":::::\"ba                    8",
            "8                  ,d::;gPPRg;::b,                  8",
            "8                  d::dP'   `Yb::b                  8",
            "8                  8::8)     (8::8                  8",
            "8                  Y;:Yb     dP:;P  O               8",
            "8                  `Y;:\"8ggg8\":;P'                  8",
            "8                    \"Yaa:::aaP\"                    8",
            "8                       \"\"\"\"\"                       8",
            "8                                                   8",
            "8                       ,d\"b,                       8",
            "8                       d:::8                       8",
            "8                       8:::8                       8",
            "8                       8:::8                       8",
            "8                       8:::8                       8",
            "8                       8:::8                       8",
            "8                  aaa  `bad'  aaa                  8",
            "\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"' `\"\"\"\"\"\"\"\"\"' `\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"",},
        {"tank",
            "                         c@t5eTAN|<",
            "                                                     _..----.._",
            "                                                    ]_.--._____[",
            "                                                  ___|'--'__..|--._",
            "                              __               \"\"\"    ;            :",
            "                            ()_ \"\"\"\"---...__.'\"\"!\":  /    ___       :",
            "                               \"\"\"---...__\\]..__] | /    [ 0 ]      :",
            "                                          \"\"\"!--./ /      \"\"\"        :",
            "                                   __  ...._____;\"\"'.__________..--..:_",
            "                                  /  !\"''''''!''''''''''|''''/' ' ' ' \\\"--..__  __..",
            "                                 /  /.--.    |          |  .'          \\' ' '.\"\"--.{'.",
            "             _...__            >=7 //.-.:    |          |.'             \\ ._.__  ' '\"\"'.",
            "          .-' /    \"\"\"\"----..../ \"\">==7-.....:______    |                \\| |  \"\";.;-\"> \\",
            "          \"\"\"\";           __..\"   .--\"/\"\"\"\"\"----....\"\"\"\"\"----.....H_______\\_!....'----\"\"\"\"]",
            "        _..---|._ __..--\"\"       _!.-=_.            \"\"\"\"\"\"\"\"\"\"\"\"\"\"\"                   ;\"\"\"",
            "       /   .-\";-.'--...___     .\" .-\"\"; ';\"\"-\"\"-...^..__...-v.^___,  ,__v.__..--^\"--\"\"-v.^v,",
            "      ;   ;   |'.         \"\"\"-/ ./;  ;   ;\\P.        ;   ;        \"\"\"\"____;  ;.--\"\"\"\"// '\"\"<,",
            "      ;   ;   | 1            ;  ;  '.: .'  ;<   ___.-'._.'------\"\"\"\"\"\"____'..'.--\"\"\";;'  o ';",
            "      '.   \\__:/__           ;  ;--\"\"()_   ;'  /___ .-\" ____---\"\"\"\"\"\"\" __.._ __._   '>.,  ,/;",
            "        \\   \\    /\"\"\"<--...__;  '_.-'/; \"\"; ;.'.'  \"-..'    \"-.      /\"/    `__. '.   \"---\";",
            "         '.  'v ; ;     ;;    \\  \\ .'  \\ ; // /    _.-\" \"-._   ;    : ;   .-'__ '. ;   .^\".'",
            "           '.  '; '.   .'/     '. `-.__.' /;;;   .o__.---.__o. ;    : ;   '\"\";;\"\"' ;v^\" .^",
            "             '-. '-.___.'<__v.^,v'.  '-.-' ;|:   '    :      ` ;v^v^'.'.    .;'.__/_..-'",
            "                '-...__.___...---\"\"'-.   '-'.;\\     'WW\\     .'_____..>.\"^\"-\"\"\"\"\"\"\"\"",
            "                                      '--..__ '\"._..'  '\"-;;\"\"\"",
            "                                             \"\"\"---'\"\"\"\"\"\"",
            "",},
        {"revolver",
            "      .____.",
            "   xuu$``$$$uuu.",
            " . $``$  $$$`$$$",
            "dP*$  $  $$$ $$$",
            "?k $  $  $$$ $$$",
            " $ $  $  $$$ $$$",
            " \":$  $  $$$ $$$",
            "  N$  $  $$$ $$$",
            "  $$  $  $$$ $$$",
            "   $  $  $$$ $$$",
            "   $  $  $$$ $$$",
            "   $  $  $$$ $$$",
            "   $  $  $$$ $$$",
            "   $  $  $$$ $$$",
            "   $$#$  $$$ $$$",
            "   $$'$  $$$ $$$",
            "   $$`R  $$$ $$$",
            "   $$$&  $$$ $$$",
            "   $#*$  $$$ $$$",
            "   $  $  $$$ @$$",
            "   $  $  $$$ $$$",
            "   $  $  $$$ $$$",
            "   $  $  $B$ $$&.",
            "   $  $  $D$ $$$$$muL.",
            "   $  $  $Q$ $$$$$  `\"**mu..",
            "   $  $  $R$ $$$$$    k  `$$*t",
            "   $  @  $$$ $$$$$    k   $$!4",
            "   $ x$uu@B8u$NB@$uuuu6...$$X?",
            "   $ $(`RF`$`````R$ $$5`\"\"\"#\"R",
            "   $ $\" M$ $     $$ $$$      ?",
            "   $ $  ?$ $     T$ $$$      $",
            "   $ $F H$ $     M$ $$K      $  ..",
            "   $ $L $$ $     $$ $$R.     \"d$$$$Ns.",
            "   $ $~ $$ $     N$ $$X      .\"    \"02h",
            "   $ 4k f  $     *$ $$&      R       \"iN",
            "   $ $$ %uz!     tuuR$$:     Buu      ?`:",
            "   $ $F          $??$8B      | '*Ned*$~L$",
            "   $ $k          $'@$$$      |$.suu+!' !$",
            "   $ ?N          $'$$@$      $*`      d:\"",
            "   $ dL..........M.$&$$      5       d\"P",
            " ..$.^\"*I$RR*$C\"\"??77*?      \"nu...n*L*",
            "'$C\"R   ``\"\"!$*@#\"\"` .uor    bu8BUU+!`",
            "'*@m@.       *d\"     *$Rouxxd\"```$",
            "     R*@mu.           \"#$R *$    !",
            "     *%x. \"*L               $     %.",
            "        \"N  `%.      ...u.d!` ..ue$$$o..",
            "         @    \".    $*\"\"\"\" .u$$$$$$$$$$$$beu...",
            "        8  .mL %  :R`     x$$$$$$$$$$$$$$$$$$$$$$$$$$WmeemeeWc",
            "       |$e!\" \"s:k 4      d$N\"`\"#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "       $$      \"N @      $?$    F$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "       $@       ^%Uu..   R#8buu$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                  ```\"\"*u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                         #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                          \"5$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                            `*$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                              ^#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                                 \"*$$$$$$$$$$$$$$$$$$$$$$$$$$>",
            "                                   `\"*$$$$$$$$$$$$$$$$$$$$$$$>",
            "                                       ^!$$$$$$$$$$$$$$$$$$$$>",
            "                                           `\"#+$$$$$$$$$$$$$$>",
            "                                                 \"\"**$$$$$$$$>",
            "                                                        ```\"\"",},
        {"riffle",
            " ,________________________________",
            "|__________,----------._ [____]  \"\"-,__  __...-----===\"",
            "        (_(||||@@@@||||)___________/   \"\"             |",
            "           `----------' Kr0gg@@[ ))\"-,                |",
            "                                \"\"    `,  _,--...___  |",
            "                                        `/          \"\"\"",},
        {"knife",
            "                                   _----..................___",
            " __,,..,-====>       _,.--''------'' |   _____  ______________`''--._",
            " \\      `\\   __..--''                |  /::: / /::::::::::::::\\      `\\",
            "  \\       `''                        | /____/ /___ ____ _____::|    .  \\",
            "   \\                           ,.... |            `    `     \\_|   ( )  |",
            "    `.                       /`     `.\\ ,,''`'- ,.----------.._     `   |",
            "      `.                     |        ,'       `               `-.      |",
            "        `-._                 \\                                    ``.. /",
            "            `---..............>",},
        {"virus",
            "     ... th3 n3w m30wcr0n var1ant ...",
            "             ,,,,,,,,",
            "           ,|||````||||",
            "     ,,,,|||||       ||,",
            "  ,||||```````       `||",
            ",|||`                 |||,",
            "||`     ....,          `|||",
            "||     ::::::::          |||,",
            "||     :::::::'     ||    ``|||,",
            "||,     :::::'               `|||",
            "`||,                           |||",
            " `|||,       ||          ||    ,||",
            "   `||                        |||`",
            "    ||                   ,,,||||",
            "    ||              ,||||||```",
            "   ,||         ,,|||||`",
            "  ,||`   ||   |||`",
            " |||`         ||",
            ",||           ||",
            "||`           ||",
            "|||,         |||",
            " `|||,,    ,|||",
            "   ``||||||||`",
            "",},
        {"girl",
            "                                    ,-=\"\"\"=.",
            "                                  .'        `.",
            "                                 (            `.",
            "                                  `.            `..",
            "                                   ,'             .'",
            "                                   `.            '.",
            "                                     `-.           `-.",
            "                                        )             `=-.",
            "                                      .'              `=-.",
            "                                    .`               .`-.",
            "                      _            (                \\ `-.",
            "                   ,'   `.          `.        /`.    \\",
            "                  /        `.         '\\      |   `.   `.",
            "                ,'            `.       )    /      \\    \\",
            "               /     .'`.        `.    )    |       `.   \\",
            "             ,'    .'    `.         `./     \\         `.  \\",
            "           ,'    .'        `.                \\          \\  \\",
            "         ,'    .'            `.               \\          `. \\",
            "       ,'   .'                 `.              )          ) (__.",
            "     ,'   (                      `.            )          `.\"\"\"'",
            " _.-'    __)                       `.         .",
            "`\"\"'\"\"                               `\"\"\"\"\"\"\"",
            "",},
        {"bear",
            " d0 n0t b3ar w1th a m30www!",
            "                  _         _",
            " .-\"\"-.          ( )-\"```\"-( )          .-\"\"-.",
            "/ O O  \\          /         \\          /  O O \\",
            "|O .-.  \\        /   0 _ 0   \\        /  .-. O|",
            "\\ (   )  '.    _|     (_)     |     .'  (   ) /",
            " '.`-'     '-./ |             |`\\.-'     '-'.'",
            "   \\         |  \\   \\     /   /  |         /",
            "    \\        \\   '.  '._.'  .'   /        /",
            "     \\        '.   `'-----'`   .'        /",
            "      \\   .'    '-._        .-'\\   '.   /",
            "       |/`          `'''''')    )    `\\|",
            "       /                  (    (      ,\\",
            "      ;                    \\    '-..-'/ ;",
            "      |                     '.       /  |",
            "      |                       `'---'`   |",
            "      ;                                 ;",
            "       \\                               /",
            "        `.                           .'",
            "          '-._                   _.-'",
            "          __/`\"  '  - - -  ' \"`` \\__",
            "         /`            /^\\           `\\",
            "         \\(          .'   '.         )/",
            "          '.(__(__.-'       '.__)__).'",
            "",},
        {"gear",
            "                    @@    00    00",
            "              0000  @@000000@@00@@XXOO@@",
            "          @@  OO0000@@000000000000@@@@OO",
            "          OO0000@@OOXXOO  @@  XXOOOO@@000000",
            "      OO    00@@00XX  00  @@  OOXX  @@@@@@00",
            "      0000@@00    00  @@  00  00  00XX  000000",
            "        0000XX00  00  00  @@  @@  00  00OO@@00@@",
            "    @@OO@@@@  XX@@  @@XXOO@@OO@@00XX00OO  XX@@@@O",
            "    OO0000XX00XXXX@@OOOO00@@00OO0000OOXX0000XX00@@0",
            "      @@00    0000XX00000000000000OO0000XX    0000",
            "  00000000@@00OOXX@@00@@@@00@@@@00@@XXXX00@@@@OO0000@",
            "    OO00XX    OO00@@@@00XX  XX00@@00@@OOXX      @@00XX0",
            "    00@@@@@@@@@@@@@@@@@@      0000@@@@@@@@@@@@@@@@00OO00",
            "XX@@00@@        OO00@@00      000000OOXX        @@@@@@",
            "      00OOOO@@00XXOO@@00000000000000XXOO@@00OOXX00XX",
            "    000000XX  OO@@OO@@00@@00@@@@00OO00OO    XX@@00@@XX",
            "  0000@@00  @@OO  @@OO0000@@00OOOO00XXOO00OO  00@@00@@",
            "      OO00@@    @@XX@@XX00@@00OO@@  @@XX  00@@0000",
            "    XX00@@@@  @@XXOOOOOOXX@@  00XX00  00XX0000@@00OO",
            "    XXXX  0000XX  @@  @@  @@  @@  00XX  0000@@    OO",
            "        OO@@000000XX  00  @@  00XX  @@00@@00@@OO",
            "        @@  OO0000@@OOOO  @@  XX0000000000  XX@@",
            "            0000@@00@@00@@@@@@@@@@00@@@@@@",
            "            00XX0000@@@@@@00@@@@00@@OO  @@",
            "        XX  000000@@@@0000  0000  00OO",},
        {"nasa",
            "... g0d sav3 th3 qu33n --- http://hacknasa.mp.ls/ ...",
            "                                    00@@@@@@@@@@@@~~~",
            "        88888b.  8888b. .d8888 @@8008b.",
            "        888  88b     88 88K@@@@ 00   88b",
            "        888  888.d888888 Y888800.d888888",
            "        888@@888888  888    0088 88  888",
            "...@@@@@888  888 Y888888 88888P' Y888888",
            "                        00",
            "                      00",
            "                    00",
            "                  00",
            "                00",
            "              00",
            "            00",
            "          00",
            "        00",
            "      00",
            "    00",
            "  00",
            "00",
            "~",},
        {"cern",
            "",
            " XXXXXXXXXXX   OO",
            "XX         XX  OO",
            "XX     @@@@@@@@@",
            "XX    OO   XX  OO",
            "XX    OO   XX  OO",
            "XX    OO   XX  OO",
            " XXXXXOOXXXX@  OO",
            " @    OO     @ OO",
            "  @   OO      @OO",
            "     @ @@@@@@@@@",
            "    @           @",},
        {"plane",
            "         .----.                                                  .'.",
            "        |  /   '                                                 |  '",
            "        |  |    '                                                '  :",
            "        |  |     '             .-~~~-.               .-~-.        \\ |",
            "        |  |      '          .\\\\   .//'._+_________.'.'  /_________\\|",
            "        |  |___ ...'.__..--~~ .\\\\__//_.-     . . .' .'  /      :  |  `.",
            "        |.-\"  .'  /                          . .' .'   /.      :_.|__.'",
            "       <    .'___/                           .' .'    /|.      : .'|\\",
            "        ~~--..                             .' .'     /_|.      : | | \\",
            "          /_.' ~~--..__             .----.'_.'      /. . . . . . | |  |",
            "                      ~~--.._______'.__.'  .'      /____________.' :  /",
            "                               .'   .''.._'______.'                '-'",
            "                               '---'",},
        {"cat",
            "... mrsPssyC4t5e - !!!Umrs4Z1Z!!! ...          .--.",
            "                                               `.  \\",
            "                                                 \\  \\",
            "                                                  .  \\",
            "                                                  :   .",
            "                                                  |    .",
            "                                                  |    :",
            "                                                  |    |",
            "  ..._  ___                                       |    |",
            " `.\"\".`''''\"\"--..___                              |    |",
            " ,-\\  \\             \"\"-...__         _____________/    |",
            " / ` \" '                    `\"\"\"\"\"\"\"\"                  .",
            " \\                                                      L",
            " (>                                                      \\",
            "/                                                         \\",
            "\\_    ___..---.                                            L",
            "  `--'         '.                                           \\",
            "                 .                                           \\_",
            "                _/`.                                           `.._",
            "             .'     -.                                             `.",
            "            /     __.-Y     /''''''-...___,...--------.._            |",
            "           /   _.\"    |    /                ' .      \\   '---..._    |",
            "          /   /      /    /                _,. '    ,/           |   |",
            "          \\_,'     _.'   /              /''     _,-'            _|   |",
            "                  '     /               `-----''               /     |",
            "                  `...-'                                       `...-'",},
        {"airport",
            " sat3ll1t3                  http://www.rfc-editor.org/rfc/rfc9450",
            "@         @",
            "@          @0@",
            "@            @0@@@",
            "@             @   @@@@",
            "@               @     @@@@",
            "@                @        @@@",
            "@                  @         @@@@",
            "@ sat3ll1t3-bas3d   @            @@@",
            "@   communications   @              0000@",
            "@      satC0M (@)     @                  0@",
            "@                      @                    a1rCraft",
            "@                       @                 @         @",
            "@                        @              @             @",
            "@                         @           @     a1r-a1r     @",
            "@                          @        @     commun1cat10ns   @",
            "@                           @     @         LDACS A/A (@)    @",
            "@                           @   @                              @",
            "@                            a1rCraft.o@0@0@0@0@0@0@0@0@0@o.a1rCraft",
            "@                                 0           a1r-gr0und           0",
            "@                                 0         commun1cat10ns         0",
            "@                                 0           LDACS a/g (0)        0",
            "@      commun1cat10ns 1n          0                                0",
            "@    and ar0und a1rp0rts          0                                0",
            "@         a3r0MACS (-)            0                                0",
            "@                                 0                                0",
            "@         a1rCraft-------------+  0                                0",
            "@                              0  0                                0",
            "@                              0  0                                0",
            "@         gr0und n3tw0rk       0  0         gr0und n3tw0rk         0",
            "satC@M <---------------------> a1rp0rt <----------------------> LDACS",
            "ground                          gr0und                         gr0und",
            "transc31v3r                   transc31v3r                 transc31v3r",},
        {"cake",
            "",
            "     )  (  )  (",
            "    (^)(^)(^)(^)",
            "    _i__i__i__i_",
            "   (____________)",
            "   |@@@@|>o<|000|",
            "   (____________)",},
        {"map",
            "90n+",
            "   |           . _..::__:  ,-\"-\"._        |7       ,     _,.__",
            "   |   _.___ _ _<_>`!(._`.`-.    /         _._     `_ ,_/  '  '-._.---.-.__",
            "   |>.{     \" \" `-==,',._\\{  \\  / {)      / _ \">_,-' `                 -2_",
            "60n+  \\_.:--.       `._ )`^-. \"'       , [_/(                       __,/-'",
            "   | '\"'     \\         \"    _L        oD_,--'                )     /. (|",
            "   |          |           ,'          _)_.\\\\._<] 6              _,' /  '",
            "   |          `.         /           [_/_'` `\"(                <'}  )",
            "30n+           \\\\    .-. )           /   `-'\"..' `:._          _)  '",
            "   |    `        \\  (  `(           /         `:\\  > \\  ,-^.  /' '",
            "   |              `._,   \"\"         |           \\`'   \\|   ?_)  {\\",
            "   |                 `=.---.        `._._       ,'     \"`  |' ,- '.",
            "000+                   |    `-._         |     /          `:`<_|h--._",
            "   |                   (        >        .     | ,          `=.__.`-'\\",
            "   |                    `.     /         |     |{|              ,-.,\\     .",
            "   |                     |   ,'           \\   / `'            ,\"     \\",
            "30s+                     |  /              |_'                |  __  /",
            "   |                     | |                                  '-'  `-'   \\.",
            "   |                     |/                                         \"    /",
            "   |                     \\.                                             '",
            "60s+",
            "   |                      ,/            ______._.--._ _..---.---------._",
            "   |     ,-----\"-..?----_/ )      __,-'\"             \"                  (",
            "   |-.._(                  `-----'                                       `-",
            "90s+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-",
            "  180w  150w  120w  90w   60w   30w   000   30e   60e   90e   120e  150e  180e",},
        {"rainbow",
            "                  \\       \\      `      /         /",
            "                                             '",
            "            \\      `    \\     `     '    /     /   `   '",
            "    \\                       .  *  *  *  *  *  .     /",
            "         `     \\    `    *  *  *  *  *  *  *  *  *       /",
            "   \\                  * * * * * * * * * * * * * * *  '",
            "       \\     `     @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @   /",
            "\\  `             * * * * *             * * * * * * * * *   '  /",
            "           `   @ @ @ @ *                 '@@@@@@@@@@@@@@@",
            "      \\      * * * * *                     * * * * * * * *  '",
            "  `        @ @ @ @ @                        @@@@@@@@@@@@@@@    /",
            "          * * * **                            * * * * * * * *",
            "\\   `   @ @ @ @ @                             @@@@@@@@@@@@@@@  '",
            "      * * * * *                                * * * * * * * * /",
            " `   @ @ @ @ @               good luck          @@@@@@@@@@@@@@@ .",
            "    * * * * *                                    * * * * * * * *.",
            "\\  @ @ @ @ @                                     @@@@@@@@@@@@@@@@",
            "  * * * * *                                         * * * * * * *",
            " @ @ @ @ @                                          @@@@@@@@@@@@@@@@",},
        {"unicorn",
            "               |))    |))",
            " .             |  )) /   ))",
            " \\\\   ^ ^      |    /      ))",
            "  \\\\(((  )))   |   /        ))",
            "   / *    )))  |  /        ))",
            "  |o  _)   ))) | /       )))",
            "   --' |     ))`/      )))",
            "    ___|              )))",
            "   / __\\             ))))`()))",
            "  /\\@   /             `(())))",
            "  \\/   /  /`_______/\\   \\  ))))",
            "       | |          \\ \\  |  )))",
            "       | |           | | |   )))",
            "       |_@           |_|_@    ))",
            "      /_/           /_/_/",},
        {"world",
            "              _-o#&&*''''?d:>b\\_",
            "          _o/\"`''  '',, dMF9MMMMMHo_",
            "       .o&#'        `\"MbHMMMMMMMMMMMHo.",
            "     .o\"\" '         vodM*$&&HMMMMMMMMMM?.",
            "    ,'              $M&ood,~'`(&##MMMMMMH\\",
            "   /               ,MMMMMMM#b?#bobMMMMHMMML",
            "  &              ?MMMMMMMMMMMMMMMMM7MMM$R*Hk",
            " ?$.            :MMMMMMMMMMMMMMMMMMM/HMMM|`*L",
            "|               |MMMMMMMMMMMMMMMMMMMMbMH'   T,",
            "$H#:            `*MMMMMMMMMMMMMMMMMMMMb#}'  `?",
            "]MMH#             \"\"*\"\"\"\"*#MMMMMMMMMMMMM'    -",
            "MMMMMb_                   |MMMMMMMMMMMP'     :",
            "HMMMMMMMHo                 `MMMMMMMMMT       .",
            "?MMMMMMMMP                  9MMMMMMMM}       -",
            "-?MMMMMMM                  |MMMMMMMMM?,d-    '",
            " :|MMMMMM-                 `MMMMMMMT .M|.   :",
            "  .9MMM[                    &MMMMM*' `'    .",
            "   :9MMk                    `MMM#\"        -",
            "     &M}                     `          .-",
            "      `&.                             .",
            "        `~,   .                     ./",
            "            . _                  .-",
            "              '`--._,dd###pp=\"\"'",},
        {"bridge",
            "                                         ^^",
            "    ^^      ..                                       ..",
            "            []                                       []",
            "          .:[]:_          ^^                       ,:[]:.",
            "        .: :[]: :-.                             ,-: :[]: :.",
            "      .: : :[]: : :`._                       ,.': : :[]: : :.",
            "    .: : : :[]: : : : :-._               _,-: : : : :[]: : : :.",
            "_..: : : : :[]: : : : : : :-._________.-: : : : : : :[]: : : : :-._",
            "_:_:_:_:_:_:[]:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:[]:_:_:_:_:_:_",
            "!!!!!!!!!!!![]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![]!!!!!!!!!!!!!",
            "^^^^^^^^^^^^[]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[]^^^^^^^^^^^^^",
            "            []                                       []",
            "            []                                       []",
            "            []                                       []",
            " ~~^-~^_~^~/  \\~^-~^~_~^-~_^~-^~_^~~-^~_~^~-~_~-^~_^/  \\~^-~_~^-~~-",
            "~ _~~- ~^-^~-^~~- ^~_^-^~~_ -~^_ -~_-~~^- _~~_~-^_ ~^-^~~-_^-~ ~^",
            "   ~ ^- _~~_-  ~~ _ ~  ^~  - ~~^ _ -  ^~-  ~ _  ~~^  - ~_   - ~^_~",
            "     ~-  ^_  ~^ -  ^~ _ - ~^~ _   _~^~-  _ ~~^ - _ ~ - _ ~~^ -",
            "        ~^ -_ ~^^ -_ ~ _ - _ ~^~-  _~ -_   ~- _ ~^ _ -  ~ ^-",
            "            ~^~ - _ ^ - ~~~ _ - _ ~-^ ~ __- ~_ - ~  ~^_-",
            "                ~ ~- ^~ -  ~^ -  ~ ^~ - ~~  ^~ - ~",},
        {"house",
            "                                                     ___",
            "                                             ___..--'  .`.",
            "                                    ___...--'     -  .` `.`.",
            "                           ___...--' _      -  _   .` -   `.`.",
            "                  ___...--'  -       _   -       .`  `. - _ `.`.",
            "           __..--'_______________ -         _  .`  _   `.   - `.`.",
            "        .`    _ /\\    -        .`      _     .`          `. _  -`.`.",
            "      .` -   _ /  \\_     -   .`  _         .`              `.   - `.`.",
            "    .`-    _  /   /\\   -   .`        _   .`                  `. _   `.`.",
            "  .`________ /__ /_ \\____.`____________.`     ___       ___  - `._____`|",
            "    |   -  __  -|    | - |  ____  |   | | _  |   |  _  |   |  _ |",
            "    | _   |  |  | -  |   | |.--.| |___| |    |___|     |___|    |",
            "    |     |--|  |    | _ | |'--'| |---| |   _|---|     |---|_   |",
            "    |   - |__| _|  - |   | |.--.| |   | |    |   |_  _ |   |    |",
            " ---``--._      |    |   |=|'--'|=|___|=|====|___|=====|___|====|",
            " -- . ''  ``--._| _  |  -|_|.--.|_______|_______________________|",
            "`--._           '--- |_  |:|'--'|:::::::|:::::::::::::::::::::::|",
            "_____`--._ ''      . '---'``--._|:::::::|:::::::::::::::::::::::|",
            "----------`--._          ''      ``--.._|:::::::::::::::::::::::|",
            "`--._ _________`--._'        --     .   ''-----.................'",
            "     `--._----------`--._.  _           -- . :''           -    ''",
            "          `--._ _________`--._ :'              -- . :''      -- . ''",
            " -- . ''       `--._ ---------`--._   -- . :''",
            "          :'        `--._ _________`--._:'  -- . ''      -- . ''",
            "  -- . ''     -- . ''    `--._----------`--._      -- . ''     -- . ''",
            "                              `--._ _________`--._",
            " -- . ''           :'              `--._ ---------`--._-- . ''    -- . ''",
            "          -- . ''       -- . ''         `--._ _________`--._   -- . ''",
            ":'                 -- . ''          -- . ''  `--._----------`--._",},
        {"flower",
            "                              ....",
            "                           ,;;'''';;,                    ,;;;;,",
            "                 ,        ;;'      `;;,               .,;;;'   ;",
            "              ,;;;       ;;          `;;,';;;,.     ,%;;'     '",
            "            ,;;,;;       ;;         ,;`;;;, `;::.  %%;'",
            "           ;;;,;;;       `'       ,;;; ;;,;;, `::,%%;'",
            "           ;;;,;;;,          .,%%%%%'% ;;;;,;;   %;;;",
            " ,%,.      `;;;,;;;,    .,%%%%%%%%%'%; ;;;;;,;;  %;;;",
            ";,`%%%%%%%%%%`;;,;;'%%%%%%%%%%%%%'%%'  `;;;;;,;, %;;;",
            ";;;,`%%%%%%%%%%%,; ..`%%%%%%%%;'%%%'    `;;;;,;; %%;;",
            " `;;;;;,`%%%%%,;;/, .. `\"\"\"'',%%%%%      `;;;;;; %%;;,",
            "    `;;;;;;;,;;//%//,.    ,;%%%%%%%        `;;;;,`%%;;",
            "           ;;;/%%%%,%/%/;;;';%%%%%%,          `;;;%%;;,",
            "          ;;;/%%%,%%%%%/;;;';;'%%%%%,             `%%;;",
            "         .;;/%%,%%%%%//;;'  ;;;'%%%%%,             %%;;,",
            "         ;;//%,%%%%//;;;'   `;;;;'%%%%             `%;;;",
            "         ;;//%,%//;;;;'      `;;;;'%%%              %;;;,",
            "         `;;//,/;;;'          `;;;'%%'              `%;;;",
            "           `;;;;'               `;'%'                `;;;;",
            "                                  '      .,,,.        `;;;;",
            "                                      ,;;;;;;;;;;,     `;;;;",
            "                                     ;;;'    ;;;,;;,    `;;;;",
            "                                     ;;;      ;;;;,;;.   `;;;;",
            "                                      `;;      ;;;;;,;;   ;;;;",
            "                                        `'      `;;;;,;;  ;;;;",
            "                                                   `;;,;, ;;;;",
            "                                                      ;;, ;;;;",
            "                                                        ';;;;;",
            "                                                         ;;;;;",
            "                                                        .;;;;'",
            "                                                       .;;;;'",
            "                                                      ;;;;;'",
            "                                                     ,;;;;'",},
        {"computer",
            "                       .,,uod8B8bou,,.",
            "              ..,uod8BBBBBBBBBBBBBBBBRPFT?l!i:.",
            "         ,=m8BBBBBBBBBBBBBBBRPFT?!||||||||||||||",
            "         !...:!TVBBBRPFT||||||||||!!^^\"\"'   ||||",
            "         !.......:!?|||||!!^^\"\"'            ||||",
            "         !.........||||                     ||||",
            "         !.........||||  ##                 ||||",
            "         !.........||||                     ||||",
            "         !.........||||                     ||||",
            "         !.........||||                     ||||",
            "         !.........||||                     ||||",
            "         `.........||||                    ,||||",
            "          .;.......||||               _.-!!|||||",
            "   .,uodWBBBBb.....||||       _.-!!|||||||||!:'",
            "!YBBBBBBBBBBBBBBb..!|||:..-!!|||||||!iof68BBBBBb....",
            "!..YBBBBBBBBBBBBBBb!!||||||||!iof68BBBBBBRPFT?!::   `.",
            "!....YBBBBBBBBBBBBBBbaaitf68BBBBBBRPFT?!:::::::::     `.",
            "!......YBBBBBBBBBBBBBBBBBBBRPFT?!::::::;:!^\"`;:::       `.",
            "!........YBBBBBBBBBBRPFT?!::::::::::^''...::::::;         iBBbo.",
            "`..........YBRPFT?!::::::::::::::::::::::::;iof68bo.      WBBBBbo.",
            "  `..........:::::::::::::::::::::::;iof688888888888b.     `YBBBP^'",
            "    `........::::::::::::::::;iof688888888888888888888b.     `",
            "      `......:::::::::;iof688888888888888888888888888888b.",
            "        `....:::;iof688888888888888888888888888888888899fT!",
            "          `..::!8888888888888888888888888888888899fT|!^\"'",
            "            `' !!988888888888888888888888899fT|!^\"'",
            "                `!!8888888888888888899fT|!^\"'",
            "                  `!988888888899fT|!^\"'",
            "                    `!9899fT|!^\"'",
            "                      `!^\"'",},
        {"phone",
            "               _.===========================._",
            "            .'`  .-  - __- - - -- --__--- -.  `'.",
            "        __ / ,'`     _|--|_________|--|_     `'. \\",
            "      /'--| ;    _.'\\ |  '         '  | /'._    ; |",
            "     //   | |_.-' .-'.'      ___      '.'-. '-._| |",
            "    (\\)   \\\"` _.-` /     .-'`_ `'-.     \\ `-._ `\"/",
            "    (\\)    `-'    |    .' .-'\" \"'-. '.    |    `-`",
            "   (\\)            |   / .'(3)(2)(1)'. \\   |",
            "   (\\)            |  / / (4) .-.     \\ \\  |",
            "   (\\)            |  | |(5) (   )'==,J |  |",
            "  (\\)             |  \\ \\ (6) '-' (0) / /  |",
            " (\\)              |   \\ '.(7)(8)(9).' /   |",
            " (\\)           ___|    '. '-.._..-' .'    |",
            " (\\)          /.--|      '-._____.-'      |",
            "  (\\)        (\\)  |\\_  _  __   _   __  __/|",
            " (\\)        (\\)   |                       |",
            "(\\)_._._.__(\\)    |                       |",
            " (\\\\\\\\\\\\\\\\\\\\)      '.___________________.'",
            "  '-'-'-'--'",},
        {"beer",
            "                         .sssssssss.",
            "                   .sssssssssssssssssss",
            "                 sssssssssssssssssssssssss",
            "                ssssssssssssssssssssssssssss",
            "                 @@sssssssssssssssssssssss@ss",
            "                 |s@@@@sssssssssssssss@@@@s|s",
            "          _______|sssss@@@@@sssss@@@@@sssss|s",
            "        /         sssssssss@sssss@sssssssss|s",
            "       /  .------+.ssssssss@sssss@ssssssss.|",
            "      /  /       |...sssssss@sss@sssssss...|",
            "     |  |        |.......sss@sss@ssss......|",
            "     |  |        |..........s@ss@sss.......|",
            "     |  |        |...........@ss@..........|",
            "      \\  \\       |............ss@..........|",
            "       \\  '------+...........ss@...........|",
            "        \\________ .........................|",
            "                 |.........................|",
            "                /...........................\\",
            "               |.............................|",
            "                  |.......................|",
            "                      |...............|",},
        {"coffee",
            "                      (",
            "                        )     (",
            "                 ___...(-------)-....___",
            "             .-\"\"       )    (          \"\"-.",
            "       .-'``'|-._             )         _.-|",
            "      /  .--.|   `\"\"---...........---\"\"`   |",
            "     /  /    |                             |",
            "     |  |    |                             |",
            "      \\  \\   |                             |",
            "       `\\ `\\ |                             |",
            "         `\\ `|                             |",
            "         _/ /\\                             /",
            "        (__/  \\                           /",
            "     _..---\"\"` \\                         /`\"\"---.._",
            "  .-'           \\                       /          '-.",
            " :               `-.__             __.-'              :",
            " :                  ) \"\"---...---\"\" (                 :",
            "  '._               `\"--...___...--\"`              _.'",
            "    \\\"\"--..__                              __..--\"\"/",
            "     '._     \"\"\"----.....______.....----\"\"\"     _.'",
            "        `\"\"--..,,_____            _____,,..--\"\"`",
            "                      `\"\"\"----\"\"\"`",},
        {"tree",
            "              * *",
            "           *    *  *",
            "      *  *    *     *  *",
            "     *     *    *  *    *",
            " * *   *    *    *    *   *",
            " *     *  *    * * .#  *   *",
            " *   *     * #.  .# *   *",
            "  *     \"#.  #: #\" * *    *",
            " *   * * \"#. ##\"       *",
            "   *       \"###",
            "             \"##",
            "              ##.",
            "              .##:",
            "              :###",
            "              ;###",
            "            ,####.",
            "/\\/\\/\\/\\/\\/.######.\\/\\/\\/\\/\\",},
        {"guitar",
            "                  _,.,",
            "                ,'   ,'",
            "               /   ,'",
            "              /   ,",
            "             /   ,",
            "            /   '",
            "           /   ,'",
            "           '.__|",
            "            |  |",
            "            |__|",
            "            |  |",
            "            |__|",
            "            |  |",
            "            |__|",
            "            |  |",
            "            |__|",
            "            |, |",
            "            |--|",
            "            |__|",
            "            |  |",
            "            |--|",
            "            |__|",
            "            |__|        ,-.",
            "            |__|'     ,'  /",
            "       _,.-'     ',_,' o /",
            "      /     8888        /",
            "      |                /",
            "       1              /",
            "       `L   8888     /",
            "        |           /",
            "       /    ====    \\",
            "      /     ____     \\",
            "     /     (____)  o  \\",
            "    /             o    \\",
            "   /             o     ,'",
            "  /               _,.'^",
            " /        __,.-\"~^",
            "',,..--~~^",},
        {"balloon",
            "             .#############.",
            "          .###################.",
            "       .####%####################.,::;;;;;;;;;;,",
            "      .####%###############%######:::;;;;;;;;;;;;;,",
            "      ####%%################%######:::;;;;;;;;@;;;;;;,",
            "      ####%%################%%#####:::;;;;;;;;;@;;;;;;,",
            "      ####%%################%%#####:::;;;;;;;;;@@;;;;;;",
            "      `####%################%#####:::;;;;;;;;;;@@;;;;;;",
            "        `###%##############%####:::;;;;;;;;;;;;@@;;;;;;",
            "           `#################'::%%%%%%%%%%%%;;;@;;;;;;'",
            "             `#############'.%%%%%%%%%%%%%%%%%%;;;;;'",
            "               `#########'%%%%#%%%%%%%%%%%%%%%%%%%,",
            "                 `#####'.%%%%#%%%%%%%%%%%%%%#%%%%%%,",
            "                   `##' %%%%##%%%%%%%%%%%%%%%##%%%%%",
            "                   ###  %%%%##%%%%%%%%%%%%%%%##%%%%%",
            "                    '   %%%%##%%%%%%%%%%%%%%%##%%%%%",
            "                   '    `%%%%#%%%%%%%%%%%%%%%#%%%%%'",
            "                  '       `%%%#%%%%%%%%%%%%%#%%%%'",
            "                  `         `%%%%%%%%%%%%%%%%%%'",
            "                   `          `%%%%%%%%%%%%%%'",
            "                    `           `%%%%%%%%%%'  '",
            "                     '            `%%%%%%'   '",
            "                    '              `%%%'    '",
            "                   '               .%%      `",
            "                  `                %%%       '",
            "                   `                '       '",
            "                    `              '      '",
            "                    '            '      '",
            "                   '           '       `",
            "                  '           '        '",
            "                              `       '",
            "                               '",
            "                              '",
            "                             '",},
        {"car",
            "                                                                       _______",
            "                                               ________......--------''       \\",
            "                                         _..-'                                 \\--.",
            "                                  -----------------------------_________________   \\",
            "                                  \\\\                                            `\\  )",
            "                                   |\\                  `.   || :         :        \\ /",
            "                                   ||                   .   '' `.........'        |/",
            "                                   ||              .----._ .| -  -   -  .  .     //",
            "                                   ||            _//     \\\\||- - . _  _       `\\//",
            "                                   |-..-------------..___  ||           \\     __|",
            "                         V        .        U             `-||         ___.---'  |",
            "                         |     . '                     .   |\\_____.--'  |       |",
            "                        ( )_-'                     .        \\           |    == |",
            "                     .-----.`-.               .            ____       ==|     .-.__",
            "             ._     /       \\  \\         .              .-'    `\\       |    /   .-\\",
            "            /::\\\\  |/---.---.\\ .-.  .                  /     ___ \\      |   /   /   \\",
            "           |::::|\\ ||||||||||./:::\\-_        ..iiii   /     /   \\ \\     |  /   / -. |",
            "        __.|::::|/ |||||||||||:::::, \\ iiiiiiiiiiii  /     / |   \\ |    | /   .'d8b\\|",
            "      .'    \\:://-_|||:F_P:|||:::::| | iiiiiiiiiiii .     / \\| / | |    |/    |   8b|",
            "   .-'       //  \\ |||||||||||\\::::|/  iiiiiiiiiiii |    .'_ \\/\\ | |  _-/     | \\ `8",
            "  /         //    \\||||||||||||`--'\\\\  ii-'       `-.    |  `-   | |-'  |     |\\   8",
            " |      _   `      |||||||||||=   -'\\\\-'          ___`\\  |----() | |    |_    |-().8",
            " |___.-' \\         ||||||||||/ \\--o\\/          .-'   `\\\\ |  _'// | | .-'  `--.|/ .8P",
            "   /    / \\        |||||||||(   )-/'         .'        \\\\\\-' /\\ /  ''      .-'| //8",
            "  /    /   \\     _-\\ \\|||||||`-'|/          /  d888b.   `\\  |/ /  '     .-'|  8_/8'",
            "8o,   .     \\ _-'.-'\\   ''''''' |          /.d8P `Q88b   \\\\\\__/  /    .'    \\ `88'",
            "`OO88o|      =/-'    `-._______/ \\        /dP' \\   \\88\\   \\\\_   /  _.'       `--'",
            "8OO `8888ooo \\\\                   `------'dP   | /  .88\\   `==-'_.'",
            "  `888o   `88888oo               _  /    .P    \\|    88 `-._____'",
            "  `   `8888ooo  `o8888oooo    _____-|   .dP_    | / |88",
            "   \\    `-._``888oo.__``8888OO8888888oo dP  `-. |   |88",
            "    \\.          /``8888ooo  OO    `-888 8           |88",
            "      `-._____.'      ``8888OO888888ooo 8------(()| 88/",
            "                                   |888 8      /\\/ /88",
            "                                   |    8     / | /88/",
            "                                   |    8    /|  /d8/",
            "                                   `    88  /   /d8/",
            "                                    \\   `88b---888/",
            "                                     \\   `888888P'",
            "                                      `-.___.-'",},
        {"bike",
            "                         _",
            "                       ,S/  .e.##ee",
            "                     ,SS/_ /#####\"\"",
            "                   ,SSSSSS`|##|",
            "                 ,'|SSSSSS/%##|",
            "                 | ;SSSSS/%%%/ .-\"\"-._                           __..ooo._.sSSSSSSSSS\"7.",
            "                 |/SSSSS/%%%/.'       `._ __               _.od888888888888\"'  '\"SSSSS\"",
            "             ___  `\"SSS/%%%/\"-.,sSSs._   8888o._    __.o888888888\"\"SS\"\"    `-._    `7Sb",
            "      _.sssSSSSSSSSSSS/`%%/ ,sSSSSSSSSS-.888888888888888888888\"'.S\"         ,SSS\"\"   `7b",
            "   ,+\"\"       ```\"\"SS/%%./,sSSSSSSSS\".   `\"888888888888888\"'.sSS\"         ,SS\"'        `S.",
            "                    /%%%/sSSSSSSSS\"   `s.   `\"88888888\"'.sSSSS\"         ,S\"'             7",
            "                   /%%%/ `SSSSSSS$$,..sSS`-.   `\"88'.sSSSSSSSS._     ,-'",
            "                  /%%%/    `SSSS$$$$SSS\",\\\\\\`-.   `\"SSSSSS\"  8\"\"\"7.-'",
            "                  /`%/      `SS$$$SSS,dP,s.\\//`-.   `SS\" ,'`8       ,ee888888ee.",
            "        ,oo8888oo/ /         `\"\"\"\",d88Pd8888./,-'/`.  `,-._`d'    ,d88888888888888b.",
            "     ,d888888888/ /8b.          d8888Pd8888888bd88b`.  :_._`8   ,888888\"'    '\"\"88888.",
            "   ,888P'      / /\"888b.       d88888`8888888Pd8888 :  :_`-.( ,d8888.__           7888b.",
            "  d88P        / /   `788b     (88888:. `8888Pd88888 ;  ; `-._ 8888P_Z_.>-\"\"--.._   `8888",
            " d88'     ,--/ /      `88b     `88888b`. `8P 78888\";  ;      `\"*88_,\"   s88s.       `888b",
            "d88'    ,',$/ /$$$$.   `88b      `8888b `. `\"'88\"_/_,'`-._         `-.d8\"88\"8P.      `888.",
            "888    ; ,$$$$$$$$$'    888        `\"8'   `---------------`-.._      8888888888       888'",
            "888    : `$$$$$$$':     888                                 '888b`-._8s888888\"P      .888'",
            "788.   `  `$$$$'  ;     88P                                  8888.   \"8878888P'      d888",
            " 88b    `.  `\"' ,'     d88'                                  '888b     '88s8\"'     .d888'",
            " `88b.    `-..-'      d88'                                    '888b.             .dd888'",
            "   788b.            ,888'                                       7888b._       _.d8888P",
            "    `7888oo..__..oo888'                                          `\"8888888888888888\"'",
            "      `\"7888888888P\"'                                               `\"788 mGk 8P\"'",},
        {"ship",
            "                                       __  o",
            "                                      /  |/",
            "                                    _/___|___________",
            "                                   /  _______      __\\",
            "   _______                        /  /_o_||__|    |",
            "    \\_\\_\\_\\______________________/___             |",
            "             \\                       \\____________|______________",
            "              \\     ||                                           |",
            "               \\  +_||_+       () () ()                      ____|",
            "                \\                                             |",
            "                 \\     _  ,,          _                      /",
            " ^^^^^^^^^^^^^^^^ \\_.=\" )\"  \"-._____,' \";__________________ /_^^^^^^^^",
            "   ^^^^  ^^^^                                              \\__|==% ^^",
            "  ^^         ^^^^^^^^       ^^^^ ^^^ ^^^^^      ^^^^^^^^^^ ^      ^^^^",
            "^^^   ^^^^          ^^^^^^^^^^^^          ^^^^     ^^       ^^^^^",},
        {"train",
            "o        o      o    o   o   o   oo  oo  oo  oo}",
            "    o     o  oo  ooo  oo  ooo ooo  ooo ooo ooo oooooo}",
            "                   oo  oo   oo  oo  ooo ooo ooo oooo ooooo}",
            "                         o    o   o   oo  oo  oo  oooo oooooo}",
            "                                        o   o   o   ooo  oo ooooo}",
            "                                                             o ooo}",
            "                                _________            \\|/         ++",
            "                    ___________ |_______|______/-\\___|-|_^_/-\\___||_n",
            "             n_____/    OOO    \\_ |[][] |----------------------|----|\\",
            "             |          (_)      ||     |______________________|_|| ||P",
            "             |          ZOO      | -----/====+______|| _---====--||- /",
            "            q|===================|_|=_/o====+|=====[__]o====+|==[__]-p\\",
            "_______________(_)(_)______(_)(_)_____\\__/_\\__/_\\__/__\\__/_\\__/_(_)____\\",},};

}
