compPAS radius
chmode radius.code $44
renOW radius.code \internet\server\radiusD.code

compPAS authen_radius
chmode authen_radius.code $64
renOW authen_radius.code \system\authentication\authen_radius.code
