compPAS dns
chmode dns.code $44
renOW dns.code \internet\server\dnsD.code

compPAS reversezone
chmode reversezone.code $24
renOW reversezone.code \internet\server\dnsZoneRev.code

compPAS updateaddr
chmode updateaddr.code $24
renOW updateaddr.code \internet\server\dnsUpdater.code
