compASM keyBoard
chmode keyBoard.code $44
renOW keyBoard.code \system\drivers\console\keyBoard.code

compASM console
chmode console.code $44
renOW console.code \system\drivers\console\console.code

compASM idle
chmode idle.code $44
renOW idle.code \system\drivers\console\idle.code

compASM nokia9110key
chmode nokia9110key.code $44
renOW nokia9110key.code \system\drivers\console\nokia9110key.code
