compPAS navigator
chmode navigator.code $24
renOW navigator.code \utils\navigator\navigator.code

compPAS bin2svg
chmode bin2svg.code $24
renOW bin2svg.code \utils\navigator\bin2svg.code

compPAS osm2bin
chmode osm2bin.code $24
renOW osm2bin.code \utils\navigator\osm2bin.code

compPAS deadend
chmode deadend.code $24
renOW deadend.code \utils\navigator\deadend.code

compPAS isis2bin
chmode isis2bin.code $24
renOW isis2bin.code \utils\navigator\isis2bin.code

compPAS ospf2bin
chmode ospf2bin.code $24
renOW ospf2bin.code \utils\navigator\ospf2bin.code

compPAS te2bin
chmode te2bin.code $24
renOW te2bin.code \utils\navigator\te2bin.code
