compPAS bugos-arm
chmode bugos-arm.code $24
renOW bugos-arm.code \utils\developer\vm-compiler\bugos-arm.code

compPAS bugos-i80386
chmode bugos-i80386.code $24
renOW bugos-i80386.code \utils\developer\vm-compiler\bugos-i80386.code

compPAS bugos-mips
chmode bugos-mips.code $24
renOW bugos-mips.code \utils\developer\vm-compiler\bugos-mips.code

compPAS bugos-powerpc
chmode bugos-powerpc.code $24
renOW bugos-powerpc.code \utils\developer\vm-compiler\bugos-powerpc.code

compPAS dos-pmodew
chmode dos-pmodew.code $24
renOW dos-pmodew.code \utils\developer\vm-compiler\dos-pmodew.code

compPAS dos-realmode
chmode dos-realmode.code $24
renOW dos-realmode.code \utils\developer\vm-compiler\dos-realmode.code

compPAS linux-i386
chmode linux-i386.code $24
renOW linux-i386.code \utils\developer\vm-compiler\linux-i386.code

compPAS windows-386
chmode windows-386.code $24
renOW windows-386.code \utils\developer\vm-compiler\windows-386.code
