noerr del etherMain.obj
make smc-arcnet.make
make smc-ultra.make
make ne-x000.make
make wd-80x3.make
make 3com-503.make
make 3com-509.make
make rtl-8139.make
make dec-200.make
make amd-lance.make
make sis-900.make
make 3com-905.make
make att-2md11.make
make dec-21x4x.make
make intel-82595.make
make intel-82559.make
make amd-pcnet32.make
make smc-9432.make
make via-vt6105.make
make rtl-8169.make
make intel-82541.make
make tmi-tc9020.make
make 3com-940.make
make bcm-57xx.make
chmode etherMain.obj 11
