compPAS iso9660
chmode iso9660.code $44
renOW iso9660.code \system\otherfs\iso9660.code

compPAS isoCreator
chmode isoCreator.code $24
renOW isoCreator.code \system\otherfs\isoCreator.code

compPAS isoExtractor
chmode isoExtractor.code $24
renOW isoExtractor.code \system\otherfs\isoExtractor.code
