compASM ideHdd
chmode ideHdd.code $44
renOW ideHdd.code \system\drivers\disks\ideHdd.code

compASM floppy
chmode floppy.code $44
renOW floppy.code \system\drivers\disks\floppy.code

compASM partition
chmode partition.code $44
renOW partition.code \system\drivers\disks\partition.code

compASM ideHddOff
chmode ideHddOff.code $44
renOW ideHddOff.code \system\drivers\disks\ideHddOff.code
