CompPAS ansi
chmode ansi.code $24
renOW ansi.code \utils\terminal\termIn-ansi.code

CompPAS ascii
chmode ascii.code $24
renOW ascii.code \utils\terminal\termIn-ascii.code

CompPAS avatar
chmode avatar.code $24
renOW avatar.code \utils\terminal\termIn-avatar.code

CompPAS chatter
chmode chatter.code $24
renOW chatter.code \utils\terminal\termIn-chatter.code

CompPAS ebcdic
chmode ebcdic.code $24
renOW ebcdic.code \utils\terminal\termIn-ebcdic.code

CompPAS hexdump
chmode hexdump.code $24
renOW hexdump.code \utils\terminal\termIn-hexdump.code

CompPAS telnet
chmode telnet.code $24
renOW telnet.code \utils\terminal\termIn-telnet.code

CompPAS raw-lsb
chmode raw-lsb.code $24
renOW raw-lsb.code \utils\terminal\termIn-raw-lsb.code

CompPAS raw-msb
chmode raw-msb.code $24
renOW raw-msb.code \utils\terminal\termIn-raw-msb.code

CompPAS vt55
chmode vt55.code $24
renOW vt55.code \utils\terminal\termIn-vt55.code

CompPAS vt102
chmode vt102.code $24
renOW vt102.code \utils\terminal\termIn-vt102.code

CompPAS vt240
chmode vt240.code $24
renOW vt240.code \utils\terminal\termIn-vt240.code

CompPAS vt420
chmode vt420.code $24
renOW vt420.code \utils\terminal\termIn-vt420.code
