CompPAS ascii
chmode ascii.code $24
renOW ascii.code \utils\terminal\proto-ascii.code

CompPAS xmodem
chmode xmodem.code $24
renOW xmodem.code \utils\terminal\proto-xmodem.code

CompPAS xmodem-1k
chmode xmodem-1k.code $24
renOW xmodem-1k.code \utils\terminal\proto-xmodem-1k.code

CompPAS xmodem-crc
chmode xmodem-crc.code $24
renOW xmodem-crc.code \utils\terminal\proto-xmodem-crc.code

CompPAS xmodem-crc1k
chmode xmodem-crc1k.code $24
renOW xmodem-crc1k.code \utils\terminal\proto-xmodem-crc1k.code

CompPAS ymodem
chmode ymodem.code $24
renOW ymodem.code \utils\terminal\proto-ymodem.code

CompPAS zmodem
chmode zmodem.code $24
renOW zmodem.code \utils\terminal\proto-zmodem.code

CompPAS kermit
chmode kermit.code $24
renOW kermit.code \utils\terminal\proto-kermit.code

CompPAS mclink
chmode mclink.code $24
renOW mclink.code \utils\terminal\proto-mclink.code
