#define ETHERTYPE_IPV4              0x0800
#define ETHERTYPE_ARP               0x0806
#define ETHERTYPE_VLAN              0x8100
#define ETHERTYPE_IPV6              0x86dd
#define ETHERTYPE_POLKA             0x8842
#define ETHERTYPE_NSH               0x894f
#define ETHERTYPE_MPLS_UCAST        0x8847
#define ETHERTYPE_MPLS_MCAST        0x8848
#define ETHERTYPE_LACP              0x8809
#define ETHERTYPE_LLDP              0x88cc
#define ETHERTYPE_PPPOE_CTRL        0x8863
#define ETHERTYPE_PPPOE_DATA        0x8864
#define ETHERTYPE_ROUTEDMAC         0x6558
#define ETHERTYPE_MACSEC            0x88e5
#define ETHERTYPE_SGT               0x8909

#define PPPTYPE_IPV4                0x0021
#define PPPTYPE_IPV6                0x0057
#define PPPTYPE_MPLS_UCAST          0x0281
#define PPPTYPE_ROUTEDMAC           0x0031
#define PPPTYPE_MACSEC              0x0053
#define PPPTYPE_SGT                 0x004a
#define PPPTYPE_NSH                 0x004b
#define PPPTYPE_POLKA               0x004d

#define IP_PROTOCOL_IGMP            2
#define IP_PROTOCOL_IPV4            4
#define IP_PROTOCOL_TCP             6
#define IP_PROTOCOL_UDP             17
#define IP_PROTOCOL_TMUX            18
#define IP_PROTOCOL_IPV6            41
#define IP_PROTOCOL_FRAG            44
#define IP_PROTOCOL_RSVP            46
#define IP_PROTOCOL_GRE             47
#define IP_PROTOCOL_ESP             50
#define IP_PROTOCOL_SWIPE           53
#define IP_PROTOCOL_SKIP            57
#define IP_PROTOCOL_ETHERIP         97
#define IP_PROTOCOL_L2TP            115
#define IP_PROTOCOL_MPLS            137
#define IP_PROTOCOL_SRL2            143
#define IP_PROTOCOL_NSH             145
