compPAS ip4
chmode ip4.code $44
renOW ip4.code \internet\kernel\ip4.code

compPAS ip4conf
chmode ip4conf.code $44
renOW ip4conf.code \internet\kernel\ip4conf.code

compPAS ip4iface
chmode ip4iface.code $44
renOW ip4iface.code \internet\kernel\ip4iface.code
