compPAS listenForwardS
chmode listenForwardS.code $44
renOW listenForwardS.code \internet\server\listenForwardS.code

compPAS listenForwardC
chmode listenForwardC.code $44
renOW listenForwardC.code \internet\server\listenForwardC.code
