compPAS pipeForwardS
chmode pipeForwardS.code $44
renOW pipeForwardS.code \internet\server\pipeForwardS.code

compPAS pipeForwardC
chmode pipeForwardC.code $44
renOW pipeForwardC.code \internet\server\pipeForwardC.code
