{$include fs_type.inc}          {types, structures, basic io}
{$include fs_disk.inc}          {disk routines, depends on media!}
{$include fs_umap.inc}          {disk usage bitmap routines}
{$include fs_inod.inc}          {inode basic io routines}
{$include fs_strm.inc}          {stream handling routines}
{$include fs_dirs.inc}          {directory io routines}
{$include fs_syst.inc}          {upper level system codes}
