compPAS makeFS
chmode makeFS.code $44
renOW makeFS.code \system\filesystem\makeFS.code

compPAS fileSys
chmode fileSys.code $44
renOW fileSys.code \system\filesystem\fileSystem.code

compPAS checkFS
chmode checkFS.code $44
renOW checkFS.code \system\filesystem\checkFS.code

compPAS clearFS
chmode clearFS.code $44
renOW clearFS.code \system\filesystem\clearFS.code

compPAS filedisk
chmode filedisk.code $44
renOW filedisk.code \system\otherfs\fd-BugOS.code
