compPAS fat12
chmode fat12.code $44
renOW fat12.code \system\otherfs\fat12.code

compPAS fat16
chmode fat16.code $44
renOW fat16.code \system\otherfs\fat16.code

compPAS fat32
chmode fat32.code $44
renOW fat32.code \system\otherfs\fat32.code

compPAS fd-fat12
chmode fd-fat12.code $44
renOW fd-fat12.code \system\otherfs\fd-fat12.code

compPAS fd-fat16
chmode fd-fat16.code $44
renOW fd-fat16.code \system\otherfs\fd-fat16.code

compPAS fd-fat32
chmode fd-fat32.code $44
renOW fd-fat32.code \system\otherfs\fd-fat32.code
