compASM printer
chmode printer.code $44
renOW printer.code \system\drivers\comm\printer.code

compASM serial
chmode serial.code $44
renOW serial.code \system\drivers\comm\serial.code

comppas serial-test
chmode serial-test.code $24
renOW serial-test.code \system\communication\serialTerm.code
