compASM speaker
chmode speaker.code $44
renOW speaker.code \system\drivers\sound\speaker.code

compASM sb16
chmode sb16.code $44
renOW sb16.code \system\drivers\sound\sb16.code

compASM adlib
chmode adlib.code $44
renOW adlib.code \system\drivers\sound\adlib.code
