compPAS userMan
renOW userMan.code \system\authentication\userManager.code

compPAS login
chmode login.code $44
renOW login.code \system\authentication\login.code

compPAS changePassword
chmode changePassword.code $64
renOW changePassword.code \system\authentication\changePassword.code

compPAS relogin
chmode relogin.code $64
renOW relogin.code \system\authentication\relogin.code

compPAS askPassword
chmode askPassword.code $64
renOW askPassword.code \system\authentication\askPassword.code

compPAS authen_constant
chmode authen_constant.code $64
renOW authen_constant.code \system\authentication\authen_constant.code

compPAS authen_passwd
chmode authen_passwd.code $64
renOW authen_passwd.code \system\authentication\authen_passwd.code

compPAS authen_local
chmode authen_local.code $64
renOW authen_local.code \system\authentication\authen_local.code

compPAS authen_securid
chmode authen_securid.code $64
renOW authen_securid.code \system\authentication\authen_securid.code

compPAS authenticator
chmode authenticator.code $64
renOW authenticator.code \system\authentication\authenticator.code
